### ISSUE TITLE
Consider a more permissive license (maybe?)

### ISSUE THREAD

**Issue by laymandaemon** [Frityet/ManagedC#11]
ManagedC is licensed under the LGPL, which does not allow static linking without the work being considered a derivative. Since ManagedC is offered as a header-only statically-linked library, all code that uses ManagedC must be licensed as LGPL as well and cannot be legally licensed differently. The code itself **could** be licensed under a more permissive license than the LGPL (e.g. ISC) but all code using ManagedC as a whole must be LGPL-licensed. Also, I Am Not A Lawyer™ and This Is Not Legal Advice™

**Comment by laymandaemon** [comment]
A solution to this problem would be licensing it more permissively, for example the Mozilla Public License 2.0 does copyleft like *GPL except it does it based on individual files instead allowing it to be linked with non-MPL code.

**Comment by Frityet** [comment]
The static linking is for the GPL, not LGPL, [im pretty sure?](https://www.reddit.com/r/rust/comments/fevz37/comment/fjsg393/)

**Comment by laymandaemon** [comment]
[Turns out it is allowed](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License)—

> Essentially, if it is a "work that uses the library", then it must be possible for the software to be linked with a newer version of the LGPL-covered program. The most commonly used method for doing so is to use "a suitable shared library mechanism for linking". Alternatively, a statically linked library is allowed if either source code or linkable object files are provided.

Sorry for making a non-issue issue! But I think a more permissive license like MPL should still be considered, but it's not nearly as big of a deal I thought it was.

**Comment by Frityet** [comment]
> [Turns out it is allowed](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License)—
> 
> > Essentially, if it is a "work that uses the library", then it must be possible for the software to be linked with a newer version of the LGPL-covered program. The most commonly used method for doing so is to use "a suitable shared library mechanism for linking". Alternatively, a statically linked library is allowed if either source code or linkable object files are provided.
> 
> Sorry for making a non-issue issue! But I think a more permissive license like MPL should still be considered, but it's not nearly as big of a deal I thought it was.

Thank you for your concern! I will look into the MPL
